server:
  port: 8089

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodbate/Spring-Cloud-Sample.git
          searchPaths: cloud-config-repo
